/**
 * Italiano Pizza
 * Italiano Pizzeria API to add new Pizzas
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IngredientModel { 
    ingredientId: number;
    name?: string;
}

